version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"
    commit-message:
      prefix: deps
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Asia/Seoul
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
    labels:
      - dependencies
